version: '3.6'
services:
  maxdb:
    image: maximo/db2
    hostname: "${DB_HOST_NAME}"
    environment:
      - MAXDB_DATADIR=/home/ctginst1/ctginst1
      - BACKUPDIR=/backup
    networks:
      - maxnet
    ports:
      - 50005:50005
    privileged: true
    volumes:
      - type: volume
        source: maxdb76
        target: /home/ctginst1/ctginst1
      - type: volume
        source: vardb2
        target: /var/db2
#      - type: bind
#        source: ./backup
#        target: /backup
  maxdmgr:
    image: maximo/maxdmgr
    hostname: "${DMGR_HOST_NAME}"
    ports:
      - 9043:9043
    environment:
      - PROFILE_NAME=ctgDmgr01
      - CELL_NAME=ctgCell01
      - NODE_NAME=ctgCellManager01
    networks:
      - maxnet
  maxapps:
    image: maximo/maxapps
    hostname: "${APP_SERVER_HOST_NAME}"
    environment:
      - PROFILE_NAME=ctgAppSrv01
      - CELL_NAME=ctgNodeCell01
      - NODE_NAME=ctgNode01
    depends_on:
      - maxdmgr
      - maxweb
      - maxdb
    networks:
      - maxnet
  maxweb:
    image: maximo/maxweb
    hostname: "${WEB_SERVER_HOST_NAME}"
    environment:
      - PROFILE_NAME=ctgWebSrv01
      - CELL_NAME=ctgNodeWSCell01
      - NODE_NAME=ctgNodeWebSrv01
    ports:
      - 80:80
    depends_on:
      - maxdmgr
    networks:
      - maxnet
  maximo:
    image: maximo/maximo
    hostname: maximo
    environment:
      - "DB_HOST_NAME=${DB_HOST_NAME}"
      - "DB_TABLE_SPACE=${DB_TABLE_SPACE}"
      - "DB_TEMP_SPACE=${DB_TEMP_SPACE}"
      - "DB_INDEX_SPACE=${DB_INDEX_SPACE}"
      - "MAXADMIN_PASSWORD=${MAXADMIN_PASSWORD}"
      - "MAXREG_PASSWORD=${MAXREG_PASSWORD}"
      - "MXINTADM_PASSWORD=${MXINTADM_PASSWORD}"
      - WAS_DM_PROFILE_NAME=ctgDmgr01
      - WAS_DM_NODE_NAME=ctgCellManager01
      - WAS_NODE_NAME=ctgNode01
      - SMTP_SERVER_HOST_NAME=localhost
      - ADMIN_EMAIL_ADDRESS=root@localhost
#      - ADD_LANGS=ja,fr
      - BASE_LANG=en
      - UPDATE_APPS_ON_REBOOT=no
      - KEEP_RUNNING=no
      - ENABLE_DEMO_DATA=no
    depends_on:
      - maxdb
      - maxapps
      - maxweb
    networks:
      - maxnet
networks:
  maxnet:
volumes:
  maxdb76:
  vardb2:
